fix: 잠재적 오류 수정

diff --git a/deploy/data/docker-compose.yml b/deploy/data/docker-compose.yml
--- a/deploy/data/docker-compose.yml
+++ b/deploy/data/docker-compose.yml
@@ -29,7 +29,13 @@ services:
   redis:
     image: redis:7-alpine
     container_name: redis
-    command: redis-server --maxmemory 768mb --maxmemory-policy allkeys-lru --requirepass ${REDIS_PASSWORD}
+    command: >
+      sh -c '
+      if [ -z "$${REDIS_PASSWORD}" ]; then
+        echo "Error: REDIS_PASSWORD is not set. Exiting." && exit 1;
+      fi;
+      redis-server --maxmemory 768mb --maxmemory-policy allkeys-lru --requirepass "$${REDIS_PASSWORD}"
+      '
     networks:
       - data-network
     ports:
@@ -37,7 +43,7 @@ services:
     volumes:
       - ./redis_data:/data
     healthcheck:
-      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
+      test: [ "CMD-SHELL", "if [ -z \"$${REDIS_PASSWORD}\" ]; then exit 1; fi; redis-cli -a \"$${REDIS_PASSWORD}\" ping" ]
       interval: 2s
       timeout: 2s
       retries: 5
